default_platform(:ios)

platform :ios do

  APP_NAME = ENV["APP_NAME"]

  lane :setup do

    version = last_git_tag

    increment_version_number_in_xcodeproj(version_number: version, scheme: APP_NAME)
    increment_build_number_in_xcodeproj(build_number: version, scheme: APP_NAME)

    update_info_plist( 
      plist_path: "#{APP_NAME}/Info.plist",
      block: proc do |plist|
        plist[:FIR_CLI_API_TOKEN] = ENV["FIR_CLI_API_TOKEN"]
      end
    )

  end
  

  private_lane :build do
    build_app(
      clean: true,
      silent: true,
      scheme: APP_NAME,
      export_method: 'ad-hoc'
    )
  end

end
