name: Apollo

on:
  push:
    tags:
      - '*'
      
  workflow_dispatch:

env:
  APP_NAME: Bingpaper
  FIR_CLI_API_TOKEN: ${{ secrets.FIR_CLI_API_TOKEN }}
  FIR_APP_CHANGELOG: CHANGELOG

jobs:
  Release:
    runs-on: macOS-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup
        uses: maierj/fastlane-action@v2.2.0
        with:
          lane: 'setup'

      - name: Build
        uses: yukiarrr/ios-build-action@v1.5.0
        with:
          scheme: ${{ env.APP_NAME }}
          export-method: "ad-hoc"
          project-path: ${{ env.APP_NAME }}.xcodeproj
          p12-base64: ${{ secrets.ALPHA_P12_BASE64 }}
          mobileprovision-base64: |
            ${{ secrets.ALPHA_PROVISION_BASE64 }}
            ${{ secrets.ALPHA_EX_PROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}

      - name: Changlog
        run: |
          sh scripts/generate_changlog.sh

      - name: Appcast
        uses: maierj/fastlane-action@v2.2.0
        with:
          lane: 'appcast'
          
          

