name: Apollo

on:
  push:
    tags:
      - '*'
      
  workflow_dispatch:

env:
  APP_NAME: Bingpaper
  CERTIFICATE_DATA: ${{ secrets.CERTIFICATE_DATA }}
  CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
  ALPHA_PROFILE_DATA: ${{ secrets.ALPHA_PROFILE_DATA }}
  ALPHA_NE_PROFILE_DATA: ${{ secrets.ALPHA_NE_PROFILE_DATA }}
  FIR_CLI_API_TOKEN: ${{ secrets.FIR_CLI_API_TOKEN }}
  FIR_APP_CHANGELOG: CHANGELOG

jobs:
  Release:
    runs-on: macOS-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup
        run: |
          sh scripts/read_mobileprovision.sh

      - name: Package
        run: |
          fastlane package
          
          

